### ISSUE TITLE
need to change coefficients

### ISSUE THREAD

**Issue by SarahBetoulMubareka** [xapple/waste_flow#1]
The waste experts need to update coefficients. How can we do that? Best to push a new excel (then I need permission)?

**Comment by xapple** [comment]
Do get push access you simply need to respond to the invitation to be a collaborator on the repository. This has been sent out last year, so you should just click on "accept".

**Comment by SarahBetoulMubareka** [comment]
Just finished the excel but when I try to push I get the following error:

git.exe push --progress "origin" master:master
remote: Permission to xapple/waste_flow.git denied to SarahBetoulMubareka.
fatal: unable to access 'https://github.com/xapple/waste_flow.git/': The requested URL returned error: 403


git did not exit cleanly (exit code 128) (2343 ms @ 15/02/2021 14:56:07)

**Comment by xapple** [comment]
On the settings page of the repository I still don't see you as a collaborator. If you go to this link what do you see?

https://github.com/xapple/waste_flow/invitations

There should be an "accept" or "join" button, whatever it is called.

**Comment by xapple** [comment]
Once that is done you probably want to switch your access method to the repository from HTTP to SSH.

This is done by editing a configuration file on your PC to specify the connection method:

 1. edit the `.git/config` file under the repository directory.
 2. find `url=`entry under section `[remote "origin"]`
 3. change it from `url=https://SarahBetoulMubareka@github.com/xapple/waste_flow.git` to    `url=git@github.com/xapple/waste_flow.git`. that is, change all the texts before `@` symbol to `ssh://git`
 4. Save the `config` file and quit. Now you could use `git push origin master` to sync your repo on GitHub.

**Comment by SarahBetoulMubareka** [comment]
Thanks a lot! I thought I had accepted yesterday but I must not have hit the button hard enough! All is ok, the new coefficients are there.Thanks a lot!
