### ISSUE TITLE
Include flagged data

### ISSUE THREAD

**Issue by selenepatani** [xapple/waste_flow#4]
At the moment flagged data such as estimated, provisional or break in time series are automatically discarded by the code.

In agreement with @SarahBetoulMubareka , we propose to include them modifying https://github.com/xapple/waste_flow/blob/c00dc4c4d30374c6c0513b80595bee092db626dd/waste_flow/zip_files.py#L122-L123
With
```
for col in map(str, years):
            # First extract potential numeric part
            df[col] = df[col].str.extract('(\d+)', expand=False)
            df[col] = df[col].apply(pandas.to_numeric, errors = 'coerce')
```

**Comment by xapple** [comment]
Hi Selene,
That sounds good. May I suggest that if you want to propose a modification to the code for review you should open a "Pull Request" instead of an "Issue". Or better yet, you can simply commit the change to the master branch after checking that all the tests pass. 👍🏻
