### ISSUE TITLE
test failed

### ISSUE THREAD

**Issue by SPatani91** [xapple/waste_flow#5]
Dear Lucas,

I made a change for the package, to include the change of APIs and input table structure https://github.com/xapple/waste_flow/commit/ec639cf155867ee1bbf7321b778412341ede0401.

Unfortunately the tests are not working in the CI https://github.com/xapple/waste_flow/actions/runs/11182949528/job/31090390997, but I'm not able to reproduce the issue since on my local machine they have been passed. If you have time, you may look at it.

Thanks a lot,

Selene

**Comment by xapple** [comment]
In the `setup.py` file, I see that pandas is fixed to an old version (1.5.3) while numpy is not fixed to any version.

Then using these specific requirements, the package is installed with pip which does not "solve" environments for compatibility issues such as miniconda does.

So either:
1) Upgrade and use latest version of pandas.
2) Downgrade numpy to an old version that used to work.
3) Use conda for the github actions testing.
